import tkinter as open

window = open.Tk()
window.title("Mark Andrei's Profile")
window.geometry("600x600")
window.resizable(False,True)
window.configure(bg="#FED1BD")
label = open.Label(window,text= "Student Profile",font= ("Fantasy",35,),fg= "black",bg= "#FED1BD",anchor="center")
label.pack(padx =5,pady=15)
label = open.Label(window,text= "Name : Mark Andrei Alba",font= ("Arial",16,),fg= "black",bg= "#FED1BD")
label.pack(padx=11,pady=9,anchor="w")
label = open.Label(window,text= "Age : 19 years old",font= ("Arial",16,),fg= "black",bg= "#FED1BD")
label.pack(padx=11,pady=9,anchor="w")
label = open.Label(window,text= "Course : BSIT",font= ("Arial",16,),fg= "black",bg= "#FED1BD")
label.pack(padx=11,pady=9,anchor="w")
label = open.Label(window,text= "Birthday : January 14, 2007",font= ("Arial",16,),fg= "black",bg= "#FED1BD")
label.pack(padx=11,pady=9,anchor="w")
label = open.Label(window,text= "Motto :",font= ("Arial",16,),fg= "black",bg= "#FED1BD")
label.pack(padx=11,pady=9,anchor="w")
label = open.Label(window,text= "Do it scared, do it tired. You'll suddenly see you've succeed.",font= ("Arial",16,),fg= "black",bg= "#FED1BD")
label.pack(padx=11,pady=9,anchor="center")
window.mainloop()